package array;

public class SubArray {

    //subarray
    //continuous part of array
    // i<=j
    //single element, complete array are subarray
    //no element is not a subarray
    //total no of subarrays -> n(n+1)/2

    //subsequence
    //any sequence that can be generated by deleting 0 or more elements from the array






}
